### ISSUE TITLE
rdfs:label okay to use in bf:Note-typed blank node?

### ISSUE THREAD

**Issue by briesenberg07** [briesenberg07/CONTENTdm-to-RDF-XML#16]
We're using a blank node of bf:Note-type for a number of the exported Cdm metadata fields. Within this blank node we are using rdfs:label and bf:noteType properties, as in:  
  
`<bf:note>
         <bf:Note>
            <rdfs:Label>Scanned from original book at 200-400 dpi in JPEG format using an Epson Expression 11000XL, resized and enhanced using Adobe Photoshop 7.01, and imported as JPEG into CONTENTdm 6.1.2.991. 2017.</rdfs:Label>
            <bf:noteType>Digital reproduction information</bf:noteType>
         </bf:Note>
      </bf:note>`  
  
Are we using **rdfs:label** correctly here? (This was mentioned during the meeting on 18 May as something to check on.)

**Comment by briesenberg07** [comment]
Also note that the bibframe notes are being used to address metadata fields that we had considered using edm:hasType for--that issue has been closed.
#9

**Comment by gerontakos** [comment]
I think it’s ok still. Note though that I used edm:hasType for something in the transform, “Category” I believe. We may want to re-think that.
---------------------------------------------------------
nameOfSender=Theodore_Gerontakos
jobTitle=Metadata&#47;Cataloging_Librarian
cellPhone=206-276-6209
officePhone=206-543-8407
---------------------------------------------------------

**Comment by briesenberg07** [comment]
Got it--thank you @gerontakos ! Closing this issue for now, reopening #9 so we can double-check our use of that property.
