### ISSUE TITLE
Does dcmi:Type StillImage actually belong in WebResource, not SourceResource?

### ISSUE THREAD

**Issue by briesenberg07** [briesenberg07/CONTENTdm-to-RDF-XML#20]

**Comment by gerontakos** [comment]
shouldn't the type be the same for all formats and versions? If it's text in print, it's text in a digital image; if it's a still image in print, it's a still image when digital. Is there something I'm not thinking of?

**Comment by briesenberg07** [comment]
Thank you Theo--this is a case of my taking a quick look at DCMI documentation yesterday and misunderstanding this DCMI type.
