### ISSUE TITLE
hcl_Collection.rdf

### ISSUE THREAD

**Issue by briesenberg07** [briesenberg07/CONTENTdm-to-RDF-XML#21]
@gerontakos : 
Draft collection file has been created in the [Capstone_data](https://drive.google.com/drive/folders/1qYP1lia_v92wwOTqc13ZKt45Rup0j_8w?usp=sharing) folder.  

The DPLA MAP calls for three properties for collections (dcmitype:Collection):
- dct:title
- dct:description
- edm:isShownAt (described in [EDM documentation](https://pro.europeana.eu/files/Europeana_Professional/Share_your_data/Technical_requirements/EDM_Documentation/EDM_Definition_v5.2.8_102017.pdf))  

The edm:isShownAt property seems like a good fit for the digital collection (**[...]55.A.2.6#digital**) but it isn't clear to me from reading the documentation whether it is appropriate for the physical collection (**[...]55.A.2.6#physical**).

**Comment by briesenberg07** [comment]
Also, coincidentally, I'm getting a funny error message in Oxygen for the edm:isShownAt property in the physical collection--maybe something in the LibGuide URL for the physical collection splash page is causing it?

**Comment by gerontakos** [comment]
Yes I see. the value of edm:isShownAt should be an edm:WebResource, so it is not appropriate to point to the page for the print collection.

I think both #physical and #digital are shownAt the same URI. I recommend this triple to point to that other page:
<https://doi.org/10.70027/uwlib.55.A.2.6#physical>
dct:isReferencedBy
<http://guides.lib.uw.edu/c.php?g=341698&amp;p=2299537> .

Note how I change the ampersand in the object-URI to &amp;
That would take care of your problem in oXygen.
 
How does that seem?

**Comment by briesenberg07** [comment]
Thank you Theo:  

Not sure I understand correctly.  
Would the idea here be to change the edm:isShownAt property in the #physical collection to a dct:isReferencedBy property with the URL for the LibGuide in the @? If so this seems easy enough.  
 
I'm confused regarding the #physical and #digital being shown at the same URI, however.  
I also can't see any change to the LibGuide URL in your reply vs. the URL I put in the Collection file draft.

**Comment by briesenberg07** [comment]
Checked in with Theo:  
We're okay with properties used as above for right now.
