### ISSUE TITLE
Agent file question

### ISSUE THREAD

**Issue by briesenberg07** [briesenberg07/CONTENTdm-to-RDF-XML#28]
How can we avoid creating duplicate triples in the agent file for Agents appearing more than once in the metadata?

**Comment by gerontakos** [comment]
Among the many ways:

(1)
Pipeline it. Write the transform that outputs the dupes, then write another that will eliminate the dupes. I could show you how to run the pipeline in oXygen using an XProc processor.
(2)
Use grouping (xsl:for-each-group). Something like this:
<xsl:result-document>
    <rdf:RDF>
        <xsl:for-each-group select=”/metadata/record” group-by=”Photographer”>
            <rdf:Description rdf:about=”{concat(‘http://doi.org/10.6069/uwlib.55.A.3.999#’,translate(current-grouping-key(), ‘-‘’ ‘’(‘’)’))}”>

Something like that, although that’s very sloppy and probably contains errors, it’s the general idea.

Note the single quotes I used in translate(). I’m thinking those are necessary, although I didn’t mention them yesterday, I forgot about them.

  --Theo

---------------------------------------------------------
nameOfSender=Theodore_Gerontakos
jobTitle=Metadata&#47;Cataloging_Librarian
cellPhone=206-276-6209
officePhone=206-543-8407
---------------------------------------------------------
